name: Semantic Release

on:
  workflow_dispatch:
    inputs:
      updateType:
        description: "version update type"
        required: true
        type: choice
        default: "patch"
        options:
          - "major"
          - "minor"
          - "patch"
      packageName:
        description: "name of the package to update"
        required: true
        type: choice
        options:
          - "ragbits-cli"
          - "ragbits-core"
          - "ragbits-dev-kit"
          - "ragbits-document-search"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.10"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update packagee
        run: |
          uv run scripts/update_ragbits_package.py ${{ github.event.inputs.packageName }} ${{ github.event.inputs.updateType }}

      - name: Commit updated packages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update ${{ github.event.inputs.packageName }} to ${{ github.event.inputs.updateType }}